### ISSUE TITLE
[Android Only]GiphyGridView content changes from GiphyContent.trendingGifs to GiphyContent.recents, GiphyGridView not refresh.

### ISSUE THREAD

**Issue by THDGunner** [Giphy/giphy-react-native-sdk#126]
- Giphy React Native SDK version: 2.4.1
- React Native version: 0.69.7
- Platform(s) (iOS, Android, or both?): Android
- Device info (Simulator/Device? OS version? Debug/Release?): Android Devices

**Comment by pshoniuk** [comment]
Hi @THDGunner 
Thank you for the report. We'll release a fix in the next version. I'll update the status here when that happens

**Comment by pshoniuk** [comment]
Hi @THDGunner 
We released a fix in [v2.4.2](https://github.com/Giphy/giphy-react-native-sdk/releases/tag/v2.4.2)

**Comment by THDGunner** [comment]
> Hi @THDGunner We released a fix in [v2.4.2](https://github.com/Giphy/giphy-react-native-sdk/releases/tag/v2.4.2)

Thank you for the quick reply!
Unfortunately this issue is not resolved yet.I upgraded to the latest(v2.4.2) version and tested it on an android device(Google pixel6).The phenomenon is the same as before.

**Comment by pshoniuk** [comment]
@THDGunner I couldn't reproduce the issue in v2.4.2. It might be a problem with the gradle cache. Please ensure your project uses the correct version of the GIPHY UI SDK, which should be: `com.giphy.sdk:ui:2.3.6-hotfix-grid`. To check this, you can inspect the output of this command running from the `android` folder: 
`./gradlew app:dependencies | grep 'com.giphy.sdk:ui'`
If the version is correct, it would be great if you could share more details or, ideally, a minimal playground where the issue occurs.
